# Generated by Django 3.2.9 on 2022-01-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('section', models.IntegerField()),
                ('campus', models.CharField(max_length=20)),
                ('DAY', models.CharField(choices=[('MN', 'Monday'), ('TU', 'Tuesday'), ('WN', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('ST', 'Satuarday'), ('SN', 'Sunday')], default='MN', max_length=2)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=20)),
                ('year_of_study', models.IntegerField()),
                ('campus', models.CharField(max_length=20)),
                ('section', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
