# Generated by Django 3.2.9 on 2022-01-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealSystem', '0002_auto_20220104_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealStatus',
            fields=[
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MealSystem.student', unique=True)),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
            ],
        ),
    ]
