# Generated by Django 3.2.9 on 2022-01-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealSystem', '0003_mealstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='student_id',
        ),
    ]
